name: CI workflow
on:
  push:
    branches: push on main branch
  pull_request:
    branches: pull_request on main branch
    
Jobs
  builds:
    runs-on: ubuntu-latest
    container: python:3.9.23-slim
    step:
    - name: Checkout
      uses: actions
    - name: Checkout
      uses: checkout@v3
      run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
